### PR TITLE
Fixed CSRF-Protector-PHP

### PR DESCRIPTION
**Pull request by evrifaessa**

### CODE REVIEW

**Comment by evrifaessa** [comment]
ugh

**Comment by timothygwebb** [comment]
@evrifaessa ugh? Explain.

**Comment by evrifaessa** [comment]
> @evrifaessa ugh? Explain.

It was just me reacting to myself realizing what a failure I am. Doesn't really mean anything.

**Comment by timothygwebb** [comment]
@evrifaessa Were you looking for this https://github.com/boxbilling/boxbilling/blob/master/src/csrfp-config.php

**Comment by evrifaessa** [comment]
> @evrifaessa Were you looking for this https://github.com/boxbilling/boxbilling/blob/master/src/csrfp-config.php
> 

Yes, I already fixed everything with a new PR. Thanks.

**Comment by BenNottelling** [comment]
I still don't understand why the variable was correctly set on my server and not yours, but I'm glad the fix was easy

**Pull request closed without merging**
