### PR TITLE
merge boxbilling:master to update:redbean

### PR DESCRIPTION
**Pull request by timothygwebb**

### CODE REVIEW

**Comment by BenNottelling** [comment]
@timothygwebb I'd like to rebase and then force push this branch rather than a messy merge like this. Any objection?

**Comment by evrifaessa** [comment]
recreating the branch is also an option

**Comment by BenNottelling** [comment]
I'm actually just going to rebase it. The only potential downside is if you guys have work based off of the branch, and I just checked to confirm that's not the case. End result is basically the same as recreating the branch

**Comment by timothygwebb** [comment]
@BenNottelling @evrifaessa I will handle the updating of this branch thanks.

**Comment by BenNottelling** [comment]
> I will handle the updating of this branch thanks.

I mean, it IS updated now. 
The only thing that should be needed from what I can tell is testing that nothing is broken and then merging it into the master branch

**Comment by timothygwebb** [comment]
Thanks for the update.

I do not see any major changes just the application of a class

You can test further and merge.

**Comment by timothygwebb** [comment]
No objections.

**Pull request merged**
