### PR TITLE
PHP 7.4.9 Update with Composer

### PR DESCRIPTION
**Pull request by timothygwebb**
Please see change log attached.
[Change log.docx](https://github.com/boxbilling/boxbilling/files/5151729/Change.log.docx)

### CODE REVIEW

**Comment by rndevuk** [comment]
@timothygwebb Looks go so far from what I've read... though i still have a lot to go through.

One thing you need to do is remove the config file. it contains details specific to you test installation, il update this posts if i spot anything else :)

**Comment by timothygwebb** [comment]
> @timothygwebb Looks good so far from what I've read... though i still have a lot to go through.
> 
> One thing you need to do is remove the config file. it contains details specific to your test installation, il update this posts if i spot anything else :)
I have deleted the bb-config.php file. 
Thanks.

**Comment by rndevuk** [comment]
You need to remove `bb-data/cache/` & `bb-data/log/` directories too along with their contents...

**Comment by timothygwebb** [comment]
> You need to remove `bb-data/cache/` & `bb-data/log/` directories too along with their contents...
@rndevuk  I have removed bb-data directories.

**Review by samapraku — COMMENTED** [review]
@timothygwebb 
This commit https://github.com/boxbilling/boxbilling/pull/628/commits/3ada75fb841746e452f25d222fd08846906cedba reverses this pull request https://github.com/boxbilling/boxbilling/pull/622.

Is there a reason for the reversal?

**Comment by rndevuk** [comment]
I think its possible that the he did it by accident. i assume he made his changes on a version of bb that was prior to pull request #622 

@timothygwebb might be worth going through your commits and pulling out all files that were not directly changes by you.. 
it seems you maybe be accidently overwriting various changes...

**Comment by samapraku** [comment]
Alright then @rndevuk.

**Comment by samapraku** [comment]
@timothygwebb I also agree to the 

https://github.com/boxbilling/boxbilling/pull/628/commits/3ada75fb841746e452f25d222fd08846906cedba#diff-c58ebdc533db078bc2374f10b5582a44L123

You've also replaced this

` if($this->di['config']['debug'] === FALSE && $event['priority'] > self::INFO) {`

with:

**Comment by timothygwebb** [comment]
> @timothygwebb
> This commit [3ada75f](https://github.com/boxbilling/boxbilling/commit/3ada75fb841746e452f25d222fd08846906cedba) reverses this pull request #622.
> 
> Is there a reason for the reversal?

The reason is with the following line of code in the pull #622 I am unable to login to the bb-admin administration area.

[root@webbhostingservices log]# diff /var/www/vhosts/webbhostingservices.com/httpdocs/boxbilling/bb-library/Box/Log.php /root/boxbilling/src/bb-library/Box/Log.php
45c45
<     protected $_min_priority = NULL;   //protected $_min_priority = array();
---
>     protected $_min_priority = NULL;
121,124c121,123
<     
<             if($this->di('config')('debug') === FALSE && $event('priority') > self::INFO) {
<           //do not log debug level messages if debug is OFF
<           //if($this->_min_priority && $priority > self::INFO) {
---
> 
>         //do not log debug level messages if debug is OFF
>         if($this->di['config']['debug'] === FALSE && $event['priority'] > self::INFO) {
166c165
< }
---
> }
\ No newline at end of file


[01-Sep-2020 16:26:12 UTC] PHP Notice:  Trying to access array offset on value of type null in /var/www/vhosts/webbhostingservices.com/httpdocs/boxbilling/bb-library/Box/Log.php on line 122

Fix to array offset I implemented 

           if($this->di('config')('debug') === FALSE && $event('priority') > self::INFO) {
          //do not log debug level messages if debug is OFF
          //if($this->_min_priority && $priority > self::INFO) {
            return ;
        }

Produced Bad Log Priority so I modified it to be 

//if($this->_min_priority && $priority > self::INFO) {

Let me know if you all have any further questions. Remember I am upgrading this to php7.4.9 and the information in the pull #622 is not to the latest and greatest. I am fixing all errors to be compliant with the version php7.4.9. and the most updated version of composer packages.

Screenshot_2020-09-01_12-35-53

**Comment by timothygwebb** [comment]
> @timothygwebb
> 
> [3ada75f#diff-c58ebdc533db078bc2374f10b5582a44L123](https://github.com/boxbilling/boxbilling/commit/3ada75fb841746e452f25d222fd08846906cedba#diff-c58ebdc533db078bc2374f10b5582a44L123)
> 
> You've also replaced this
> 
> ` if($this->di['config']['debug'] === FALSE && $event['priority'] > self::INFO) {`
> 
> with:
> `if($this->_min_priority && $priority > self::INFO) `
> 
> Could you also explain why? I think it should only log debug messages if debugging is enabled.
> Is there a problem with the existing behaviour?

@samapraku Explanation included with prior comment.

**Comment by timothygwebb** [comment]
> [](https://github.com/boxbilling/boxbilling/pull/622)
> 
> @timothygwebb might be worth going through your commits and pulling out all files that were not directly changed by you and also check that you are using the latest master branch for these changes...
> it seems you maybe be accidentally overwriting various changes...

I did pull the master before making these changes and re-based by request of @fordnox for my prior pull request that I closed for this one to replace. Please let me know if you all have any further questions.

**Comment by rndevuk** [comment]
Appologies @timothygwebb I assumed wrongly. :)

**Comment by samapraku** [comment]
@timothygwebb 
I get your explanation. However, I was mainly focusing on the first part.

The if condition has two parts, the first part `if($this->di['config']['debug'] === FALSE && ...)` checks if debug is enabled in the bb-config file before logging debug messages but you left that out so it means that debug messages will be logged regardless of whether debug is set to true or false in bb-config. 

Is the configuration value check not compatible with PHP 7.4?

**Comment by timothygwebb** [comment]
> @timothygwebb
> I get your explanation. However, I was mainly focusing on the first part.
> 
> The if condition has two parts, the first part `if($this->di['config']['debug'] === FALSE && ...)` checks if debug is enabled in the bb-config file before logging debug messages but you left that out so it means that debug messages will be logged regardless of whether debug is set to true or false in bb-config.
> 
> Is the configuration value check not compatible with PHP 7.4?
@samapraku I have pushed change to switch variable back to 'NULL'.
It works again now with your modification.
Thanks for the catch.

**Pull request merged**
