### PR TITLE
Update initial install SQL Query

### PR DESCRIPTION
**Pull request by rndevuk**
The default extension_meta was missing from the production install query which was causing all event hooks to not be called.

Fixes issue #624

### CODE REVIEW

**Comment by samapraku** [comment]
If I'm not mistaken, the hooks are initialised at the first cron job run and gets updated if it needs to be, each time the cron job executes.

Check: https://github.com/boxbilling/boxbilling/blob/5f270ebf992548b08ad1b27f5e0a1b18c205a611/src/bb-modules/Cron/Service.php#L56

So you only need to configure cron job after initial installation and this will be taken care off.

In my opinion, I do not think inserting into the database directly is necessary.

**Comment by rndevuk** [comment]
@samapraku thank you for that information. i didn't notice it..

Maybe the setup script should manually run the cron job after it has completed?

**Comment by samapraku** [comment]
Making the setup script execute the cron job is an option. 

The  hook_batch_connect method can also be called via the system api to initialize only the hooks without necessarily running all the cron job.
 
The installation completed page already includes information about post-install steps which must be performed which includes setting up cron job. 

Another option will be to update the information/page to reflect that the cron job is required for boxbilling to run correctly.

**Comment by rndevuk** [comment]
In my case i currently use it for development work only so i have no need to use the cron jobs. I'm sure there are a few others with similar situations.

Ideally. i think the best is the run the hook_batch_connect method at the end of the install.. that seems like the route that would cause the least amount of confusion. Il close this merge request for now and will update the setup script when i get time during the week.

**Pull request closed without merging**
