### PR TITLE
Update Countries in BoxBilling

### PR DESCRIPTION
**Pull request by notbasetwo**
BoxBilling has not had a review of the countries it includes by default, and a few other small things since 2015 from what I can tell.

Since the last update (and even further back), several territories have undergone name changes and they have been added.

Previously the developer(s) arbitrarily left out several territories that are inhabited, which I have also added to the list.

Finally, I have updated the EU VAT rates as some of these have changed since 2015 and removed the UK from being classified as an EU country, as it is no longer in the EU.

### CODE REVIEW

**Comment by evrifaessa** [comment]
Thanks for the update. Can you push a dummy commit to your fork to trigger Travis CI again? It won't work for first-time contributors for some reason.

**Comment by BenNottelling** [comment]
Thank for the PR, these changes look good to me. Think you could take a look at this? I tested to confirm it still doesn't work as intended with this PR
https://github.com/boxbilling/boxbilling/issues/945

**Comment by notbasetwo** [comment]
> 
> 
> Thank for the PR, these changes look good to me. Think you could take a look at this? I tested to confirm it still doesn't work as intended with this PR
> #945

My plan was to have a look at that next, got a few questions that might make that issue a little bit larger though.

This PR should (although un-intended) make country detection more reliable after that issue is sold now that the ISO codes have been tidied up.

**Comment by BenNottelling** [comment]
> My plan was to have a look at that next

I'm happy to merge this in the mean-time. Once @John-S4 is feeling better and get's the stripe integration updated, I want to get another beta release put out, so at the moment I'm glad to merge in even small fixes so we can get as many bug fixes and quality of life changes in before the next beta

**Review by BenNottelling — APPROVED** [review]

**Comment by notbasetwo** [comment]
As mentioned in #945 - correct attribution for GeoLite2 data has now been included.

**Pull request merged**
