### PR TITLE
Removed leftovers of AlertPay, SinglePay, WebToPay and Payza

### PR DESCRIPTION
**Pull request by evrifaessa**
- [x] Remove leftovers from the base code
- [x] Update bb-update to remove the adapters from existing installations' database

### CODE REVIEW

**Comment by BenNottelling** [comment]
Thanks, I didn't know those were there

**Comment by BenNottelling** [comment]
@evrifaessa There are also some unused images now.
Inside `bb-themes\huraga\assets\img\gateway_logos`
`alertpay.png`, `alipay.png`, `webtopay.png`, and `simplepay.png`

**Comment by evrifaessa** [comment]
> 
> 
> @evrifaessa There are also some unused images now.
> Inside `bb-themes\huraga\assets\img\gateway_logos`
> `alertpay.png`, `webtopay.png`, and `simplepay.png`

Done. Thanks.

**Review by BenNottelling — APPROVED** [review]

**Comment by BenNottelling** [comment]
If you can have bb-update remove the adapters from existing installations' database, that would be nice, but if not this is still fine imo. I doubt there are all that many people using the last release of BB anyways

**Comment by evrifaessa** [comment]
> I doubt there are all that many people using the last release of BB anyways

Not true. In fact, the latest beta (v4.22-beta.1) of BB was downloaded 5 times more than the latest stable release (v4.21).
See more here: [link](https://somsubhra.github.io/github-release-stats/?username=boxbilling&repository=boxbilling&page=1&per_page=5

**Comment by BenNottelling** [comment]
> Not true. In fact, the latest beta (v4.22-beta.1) of BB was downloaded 5 times more than the latest stable release (v4.21).
> See more here: [link](https://somsubhra.github.io/github-release-stats/?username=boxbilling&repository=boxbilling&page=1&per_page=5)

Whoa, I didn't know there was a way to check those stats, cool! 
Well, in that case ignore what I said lol

**Comment by BenNottelling** [comment]
@evrifaessa Forgot to mention, I also removed payza. I think there are just messages and the payza logo to remove

**Comment by evrifaessa** [comment]
> @evrifaessa Forgot to mention, I also removed payza. I think there are just messages and the payza logo to remove

Done, thanks.

**Pull request merged**
