### PR TITLE
Add missing PHPMailer namespaces

### PR DESCRIPTION
**Pull request by rndevuk**
Without these sending emails from the app will not work and will throw missing class exceptions.

### CODE REVIEW

**Comment by rndevuk** [comment]
It's worth noting that this has possibly come from the the recent composer updates and there is likely to be more missing namespace declarations throughout the project.

**Comment by samapraku** [comment]
That is a bit strange. I have just done a fresh installation from the master and emails are generated and sent without any exceptions.

Did you run `composer update` or `composer install` for the recent updates?

**Comment by rndevuk** [comment]
Hi @samapraku 

I saw your reply come through via email but i don't see it on here. To answer your question the reason the installer is able to send emails out without any exceptions is because it doesnt use PHPMailer. it uses php's builtin mail functions as seen here:

```php
private function _sendMail($ns)
    {
        $admin_name = $ns->get('admin_name');
        $admin_email = $ns->get('admin_email');
        $admin_pass = $ns->get('admin_pass');

        $content = "Hi $admin_name, " . PHP_EOL;
        $content .= "You have successfully setup BoxBilling at " . BB_URL . PHP_EOL;
        $content .= "Access client area at: " . BB_URL . PHP_EOL;
        $content .= "Access admin area at: " . BB_URL_ADMIN . " with login details:" . PHP_EOL;
        $content .= "Email: " . $admin_email . PHP_EOL;
        $content .= "Password: " . $admin_pass . PHP_EOL . PHP_EOL;

        $content .= "Read BoxBilling documentation to get started http://docs.boxbilling.com/" . PHP_EOL;
        $content .= "Thank You for using BoxBilling." . PHP_EOL;

        $subject = sprintf('BoxBilling is ready at "%s"', BB_URL);

        @mail($admin_email, $subject, $content);
    }
```

**Comment by samapraku** [comment]
I have confirmed this. 

It is caused by https://github.com/boxbilling/boxbilling/pull/603

It has been stated in the PHPMailer readme:
https://github.com/PHPMailer/PHPMailer

**Comment by samapraku** [comment]
> Hi @samapraku
> 
> I saw your reply come through via email but i don't see it on here. To answer your question the reason the installer is able to send emails out without any exceptions is because it doesnt use PHPMailer. it uses php's builtin mail functions as seen here:
> 

I deleted my first comment because I realised that I did the test on a different installation.

**Review by fordnox — APPROVED** [review]

**Pull request merged**
