### PR TITLE
Rewrite stuff related to Docker, the installer script and nginx

### PR DESCRIPTION
**Pull request by evrifaessa**
This should get Docker working again.

- Rewritten the Docker Compose specification
- Docker now uses MariaDB 10.7 instead
- Written an installer script that automatically installs BoxBilling on Docker. (bin/install.sh)
- The installer rebuilds BoxBilling, wakes the container up, runs the preparation script, installs Composer dependencies and finally removes the install folder so the user can jump right in
- The problem that prevented administrators from creating their accounts using the web panel is now fixed
- The problem with assets not loading is now fixed
- `make all` will now launch the new script and let it handle the installation task

Just to note, I'm not really experienced with Docker and I'd love to hear some opinions before merging this.

See it in action:
[Click to see the GIF](https://yagiz.dev/box.gif)

I'm planning to make some changes to the CLI installer in the future. I've left some ideas here:
https://github.com/boxbilling/boxbilling/blob/fd4f0bdf9229e3f057f1ccade9492961c4ff84b1/bin/install.sh#L12-L22

Related issues: #1292 and #1138.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Docker now uses MariaDB 10.7 instead

Consider using 10.6. 10.6 is an LTS release and 10.7 only receives updates for 1 year.

**Comment by evrifaessa** [comment]
> Consider using 10.6. 10.6 is an LTS release and 10.7 only receives updates for 1 year.

Tested, works, pushed. 👍🏻

**Comment by jaapmarcus** [comment]
Also 

ERROR
Unable to create the cache directory (/var/www/html/src/bb-data/cache/09).

**Comment by evrifaessa** [comment]
> Also 
> 
> ERROR
> Unable to create the cache directory (/var/www/html/src/bb-data/cache/09).

Yeah... I also have this error. For some reason it doesn't have permissions to write on the data folders. We should look into that.

**Comment by evrifaessa** [comment]
But uh... By default nginx, PHP and MariaDB run as root. How can't they create a directory?

**Comment by evrifaessa** [comment]
In my case, on Manjaro Linux, changing the ownership to the `http` user fixed the thing.

`sudo chown -R http boxbilling`

However, I assume the username changes from distro to distro, how can we know this and possibly integrate the process to the installer?

**Comment by jaapmarcus** [comment]
Ubuntu default http user is by default www-data  Unless we supply the base image it would be quite hard to keep it the same on each OS

**Comment by evrifaessa** [comment]
> ERROR Unable to create the cache directory (/var/www/html/src/bb-data/cache/09).

@jaapmarcus Can you pull from the branch and try again? It now automatically sets 777 permissions to necessary folders.

**Comment by timothygwebb** [comment]
> > ERROR Unable to create the cache directory (/var/www/html/src/bb-data/cache/09).
> 
> @jaapmarcus Can you pull from the branch and try again? It now automatically sets 777 permissions to necessary folders.

I never like to use world writable  permissions on anything. Further investigate this path we may need to modify more than just one folders permissions to allow this to function across all distributions or consider adding the SUID bit such as  chmod u+s  filename.

**Comment by evrifaessa** [comment]
> I never like to use world writable  permissions on anything. Further investigate this path we may need to modify more than just one folders permissions to allow this to function across all distributions or consider adding the SUID bit such as  chmod u+s  filename.

Can you demonstrate that?

**Comment by evrifaessa** [comment]
@timothygwebb @jaapmarcus 

The docs and the existing installers already prompt users to chmod 777 those directories. I made changes based on the already-existing practices but yeah, we can change them.

I'd still be glad if you demonstrated some possible ways to achieve this. You can also make changes on the "docker" branch. Thanks.

https://github.com/boxbilling/boxbilling/blob/245ffd786c2d8ae61b90703671289aad06b4e936/src/bb-locale/en_US/LC_MESSAGES/messages.po#L2185-L2193

https://github.com/boxbilling/boxbilling/blob/245ffd786c2d8ae61b90703671289aad06b4e936/bin/install.sh#L10-L11

https://github.com/boxbilling/docs/blob/master/docs/reference/faq.rst#cache-folder-is-not-writable

https://github.com/boxbilling/docs/blob/5c454aa2c3228082ac0f953ea191bd3d14285d99/docs/reference/installation.rst#using-web-installer

**Comment by timothygwebb** [comment]
@evrifaessa 
Here is how you do what I have requested.
Final Result captured below. 
image
commands to obtain capture are as follows.

image
image
Update your script to execute the above commands and let me know the outcome.
Let me know if you have any further questions.

> @timothygwebb @jaapmarcus
> 
> The docs and the existing installers already prompt users to chmod 777 those directories. I made changes based on the already-existing practices but yeah, we can change them.
> 
> I'd still be glad if you demonstrated some possible ways to achieve this. You can also make changes on the "docker" branch. Thanks.
> 
> https://github.com/boxbilling/boxbilling/blob/245ffd786c2d8ae61b90703671289aad06b4e936/src/bb-locale/en_US/LC_MESSAGES/messages.po#L2185-L2193
> 
> https://github.com/boxbilling/boxbilling/blob/245ffd786c2d8ae61b90703671289aad06b4e936/bin/install.sh#L10-L11
> 
> https://github.com/boxbilling/docs/blob/master/docs/reference/faq.rst#cache-folder-is-not-writable
> 
> https://github.com/boxbilling/docs/blob/5c454aa2c3228082ac0f953ea191bd3d14285d99/docs/reference/installation.rst#using-web-installer

**Pull request closed without merging**
