### PR TITLE
WYSIWYG rewrite

### PR DESCRIPTION
**Pull request by evrifaessa**
This PR drops the support for the 7 year old editor markitUp. Instead, it makes CKEditor (which also was 7 year old, but has regular updates) the default editor.

Now, we have the newest version of CKEditor 4, and WYSIWYG is enabled on new installations by default. I'll work on getting custom pages working with raw HTML input, as that's how CKEditor outputs text.

CKEditor on action

### CODE REVIEW

**Comment by BenNottelling** [comment]
Wow, this introduces a lot of issues into the code analysis

**Comment by evrifaessa** [comment]
> Wow, this introduces a lot of issues into the code analysis

I'll try getting CKEditor 5 working in the not-so-near future. But until then, I thought it's better to have somehow new version of a 7 year old editor.

**Review by BenNottelling — CHANGES_REQUESTED** [review]
It looks like we only use the moono skin, but you're adding the moono-lisa skin to the repository.
Unless it's possible for the end user to switch between the two, please update one and get rid of the other

**Comment by evrifaessa** [comment]
> It looks like we only use the moono skin, but you're adding the moono-lisa skin to the repository.
> Unless it's possible for the end user to switch between the two, please update one and get rid of the other

We're using the newer one, aren't we? I thought I deleted the old one from the repository. Can you point me where it is?

**Comment by BenNottelling** [comment]
> We're using the newer one, aren't we? I thought I deleted the old one from the repository. Can you point me where it is?

Disregard, you're right!

**Review by BenNottelling — APPROVED** [review]

**Comment by evrifaessa** [comment]
Alright, let's merge this and see how it goes for a while.

**Pull request merged**
