### PR TITLE
Update to Bootstrap 5

### PR DESCRIPTION
**Pull request by andpavlenko**
- Rewrited templates to HTML5 with responsive design.
- Moved JS loading to bottom page. Small changes was necessary, but I leave it simple as possible - for future work.
- Replace Bootbox with native Bootstrap Toast.
- #1265 Update Bootswatch themes.
- Added Favicon to theme settings.

p.s. Good design ideas a welcome!

Screenshot from 2022-04-16 12-02-16
Screenshot from 2022-04-16 12-08-33
Screenshot from 2022-04-16 12-19-15
Screenshot from 2022-04-16 12-20-02
Screenshot from 2022-04-16 12-33-57

### CODE REVIEW

**Comment by evrifaessa** [comment]
Andrey, thanks for the PR :) This PR will likely need to go under some community approval given the scope of the changes.

In the late stages of the discussion, I'll announce this PR on our Discord server and seek more input from the community.

**Comment by evrifaessa** [comment]
The login/register page looks kind of unsteady.

Clicking the link in the sidebar will take you to this page:

Imgur

The problem is, while the register form is located within the page, the login form is a modal.

Imgur

Imgur

I think we should have both within the page, preferably call a modal when the links in the main navbar are clicked.

**Comment by givinghawk** [comment]
i can also spot some bad translation, "Registration" should be "Register" in the header, breadcrumb, the swap button and the submit button

**Comment by givinghawk** [comment]
i will have a look at the code on my own install to check for any other translation errors or general errors and i will add a comment with a review in about 1 or 2 hours

**Comment by givinghawk** [comment]
Here is my review as promised:

Unreadable text on the home page panels
image

Translation error, "Registration" should be "Register"
image
image

Error with logo sizing on the dashboard
image
image
image_2022-04-17_105851499

Random empty list group under main list group of the sidebar
image

Error thrown when viewing emails
image

That is all errors I could find, if you want me to make a PR on your fork, just let me know (I will respond fastest on discord Givinghawk#4893)

**Comment by andpavlenko** [comment]
@evrifaessa 
> The problem is, while the register form is located within the page, the login form is a modal.

Fixed.

@givinghawk 
> Error with logo sizing on the dashboard

Fixed.

> Random empty list group under main list group of the sidebar

Simple disable `Show sidebar note` in theme settings.

> Error thrown when viewing emails

Can't find how send Email to client with BB. My list is always empty.

> Translation error, "Registration" should be "Register"

"Register" its a right form for native speakers?

**Comment by andpavlenko** [comment]
@givinghawk 
> Error thrown when viewing emails

I finded same error only in admin_default template of Massmailer. Fixed it.

p.s. Please, in your report give full information how to reproduce problem!

**Comment by andpavlenko** [comment]
All fixed! What other wishes? ))

**Comment by givinghawk** [comment]
i will have another look at this pr quickly on my install

**Comment by givinghawk** [comment]
as promised, here is my review:

Width error with custom fields on registration
image

Country dropdown does not show up on register page
image

apart from that, it is perfect!

**Review by givinghawk — APPROVED** [review]
from what i can see, all of the files are fine too!

**Comment by andpavlenko** [comment]
Added registration in modal window. Test it...

**Comment by andpavlenko** [comment]
Added stats panes with settings:

Screenshot
Screenshot (2)

**Comment by evrifaessa** [comment]
Login button in `/forum/forum-rules` doesn't work.

Also, invoice pages (`/invoice/*`) crash with this error. not sure if it's related to the theme though:

Twig\Environment::getTemplateClass(): Argument #1 ($name) must be of type string, null given, called in /srv/http/bb-vendor/twig/twig/src/Environment.php on line 309

Other than that, it looks fine to merge. We can work on other issues after merging the PR.

**Pull request merged**
