### PR TITLE
Added mysqli support to replace old deprecated mysql functions

### PR DESCRIPTION
**Pull request by RohanSakhale**
In the installation module, old MySQL deprecated functions were used, I have updated the same using mysqli object oriented way.

### CODE REVIEW

**Comment by psycholyzern** [comment]
Seems that boxbilling is back!

**Comment by NatarajaVj** [comment]
Fantastic!

**Comment by TuxMay** [comment]
We never left & we do closely monitor our GitHub & we do still respond to support tickets.

**Comment by Eiskaltereistee** [comment]
you say "We never left", while you merging a pull request from 2016.... :D

**Comment by TuxMay** [comment]
I have been looking at this GitHub for 2 years, I did this pull request now as it was authorised - I'm looking at 4 pull requests currently to be merged. I'm sorry if you believe this is well overdue.

**Pull request merged**
