### PR TITLE
Add custom buttons

### PR DESCRIPTION
**Pull request by givinghawk**
Copy and paste of custom footer links but its now edited so when you go to manage an order it shows buttons if enabled.

### CODE REVIEW

**Comment by BenNottelling** [comment]
Any customization here will get overridden as soon as you update BB

**Comment by givinghawk** [comment]
> Any customization here will get overridden as soon as you update BB

Yes that is why I am making a pr

**Comment by timothygwebb** [comment]
@givinghawk @BenNottelling For further explanation what I think @BenNottelling  means is that the way bootstrap works your changes will be overriden by the css from bootstrap. @BenNottelling please clarify further.

**Comment by givinghawk** [comment]
> @givinghawk @BenNottelling For further explanation what I think @BenNottelling means is that the way bootstrap works your changes will be overriden by the css from bootstrap. @BenNottelling please clarify further.

I did not touch the css, it is just on the config page and order manage page

**Comment by BenNottelling** [comment]
No, @timothygwebb 
Anything that is in this GitHub repository will be overridden when BB updates.
So any kind of customization to the buttons will be erased with every update.
The only way to not do that is load load them from the database or some other file that is not part of our repository

**Comment by givinghawk** [comment]
Or people can just re set them every update? I am also thinking of doing a
pterodactyl integration pr.

**Comment by timothygwebb** [comment]
> No, @timothygwebb Anything that is in this GitHub repository will be overridden when BB updates. So, any kind of customization to the buttons will be erased with every update. The only way to not do that is load them from the database or some other file that is not part of our repository
@BenNottelling Thanks for the clarification. @givinghawk If you need help on the implementation of the suggestions given by @BenNottelling  please feel free to reach out to myself or @BenNottelling

**Comment by BenNottelling** [comment]
> Or people can just re set them every update?

If that's the intention then this PR may as well not exist, honestly.
I'd be more than happy to consider a PR adding custom buttons, but only if it's implemented correctly & not in a way that gets broken with every PR

**Comment by timothygwebb** [comment]
I am in agreement with Ben.

**Comment by givinghawk** [comment]
Would it be possible to add a single json file that stores the options?

**Comment by jaapmarcus** [comment]
It makes sense to allow the "Connector" between Boxbilling / Pterodactyl to have certain settings injected the "admin" page, user interface and so on.. How it should be done is a diferrent story off course

**Comment by givinghawk** [comment]
> It makes sense to allow the "Connector" between Boxbilling / Pterodactyl to have certain settings injected the "admin" page, user interface and so on.. How it should be done is a diferrent story off course

I will try to add it locally on my server.

**Comment by givinghawk** [comment]
i have improved this and put it in PR #1263

**Pull request closed without merging**
