### PR TITLE
Fix our updater and use GitHub releases

### PR DESCRIPTION
**Pull request by BenNottelling**
- Update endpoints to GitHub
- Update `file_get_contents` to optionally not use offset, since github doesn't work with that
- Fix URLHelper
- Use [php-zip](https://github.com/Ne-Lexa/php-zip) instead of old library that isn't maintained.

I think this works, but my file permissions are causing errors. Will do more testing and report back
Edit: It downloads and extracts as it should

### CODE REVIEW

**Comment by BenNottelling** [comment]
Yağızhan told me this looked good in a DM, but I'd love to hear from some other contributors before merging

**Review by evrifaessa — APPROVED** [review]
LGTM

**Comment by BenNottelling** [comment]
@notbasetwo would you mind reviewing this?

**Review by notbasetwo — APPROVED** [review]
Looks good to me! Tested it on my machine and all seems well.

Happy that the zip library has been moved in to composer too. Good work :)

**Comment by BenNottelling** [comment]
@notbasetwo thanks!

**Pull request merged**
