### PR TITLE
Include a slightly modified version of CSRF-Protector-PHP

### PR DESCRIPTION
**Pull request by BenNottelling**
This version of [CSRF-Protector-PHP ](https://github.com/mebjas/CSRF-Protector-PHP) is just modified to allow the config file (now called ```csrfp-config.php```) to reside in the same folder as ```bb-config.php```.

Normally I wouldn't want to include a lib like this since it can't auto update, but the original lib hasn't updated since oct 2020.
This should close https://github.com/boxbilling/boxbilling/issues/881 and conveniently this lib is supposed to automatically work with any forum on we add on the website, so we shouldn't have to ensure it's added when needed with each contribution.

I don't know how to test this and ensure everything works as it should. 

Also, maybe we should consider an HTTPS only option for BoxBilling? SSL is very easy to get these days and IMO is needed if you have anything more than a static webpage

### CODE REVIEW

**Comment by BenNottelling** [comment]
Failed checks are code warnings from CSRF-Protector-PHP and not my work, do we fix it?

**Comment by timothygwebb** [comment]
@BenNottelling Fix it at the source and let the maintainer merge it in then reapply.

**Comment by timothygwebb** [comment]
@BenNottelling Thanks for the draft of your pull request.

**Comment by BenNottelling** [comment]
I won't be removing the TODO's. Those should be turned into a warning in CodeFactor and not a fail

**Comment by BenNottelling** [comment]
@timothygwebb Can you confirm the fail CodeQL gives is correct? I don't want to mess with a replace function like this as I don't know if it's deliberate or not

**Comment by timothygwebb** [comment]
I will look into it and get back to you.

Thanks

Timothy Webb Sr.

**Comment by BenNottelling** [comment]
Does anyone have anything for me to change before I merge?

**Comment by evrifaessa** [comment]
Does this work on PHP 8?

**Comment by evrifaessa** [comment]
Also, it'd be very nice if we don't go with a modified version. It means extra work for us to keep our fork even with the origin. I'm afraid this will turn out to have the same end with our forks of 7 year old packages that we never had time to maintain.

**Comment by BenNottelling** [comment]
> Does this work on PHP 8?

When I changed my instance to PHP 8, I get this when trying to login, with or without the protection module being loaded inside of `bb-load.php`. 
`Call to undefined function RedBeanPHP\new\ArrayIterator()
`

I find this strange, as I thought I've had a BB instance working on PHP 8 before. I'll have to do a clean install and try again

**Comment by BenNottelling** [comment]
> It means extra work for us to keep our fork even with the origin

Origin hasn't show any sign of life since October 16th, 2020. If they do update, the only modifications are this
https://github.com/boxbilling/boxbilling/pull/926/files?file-filters%5B%5D=.md&file-filters%5B%5D=.php#diff-20508a4d5810d789413daad8bdf0ec2b1213c3e75a0117ba1a5a6a1d22c70b22R140
And, I also updated the JS file based on coed analysis and this comment:
https://github.com/mebjas/CSRF-Protector-PHP/commit/df629c87e4b7b5408d32f1692ea8c93fb5ac8e4e#commitcomment-52126505

Also, on the subject of PHP8 giving that error, I can confirm it happens even on a fresh instance from the master branch

**Comment by evrifaessa** [comment]
Well, it may not be a necessity but I still think it would be a better practice to leave the updating part to composer. If it's not possible now, I'm okay with that. But still would be glad to get rid of external packages from our base code, and get every dependancy handled by Composer.

I still approve these changes, and thanks for your work :)

**Comment by evrifaessa** [comment]
Well, I'm okay with the changes. But not sure if anyone else would raise another concern. Merging is up to you :)

**Comment by BenNottelling** [comment]
Sounds like Timothy has no objections so I'm merging this

**Comment by timothygwebb** [comment]
Your php8 will work after you go to this website and follow
directions. RedBeanPHP
:: Install <https://www.redbeanphp.com/index.php?p=/install>

**Pull request merged**
