### PR TITLE
Initial implementation of a CWP server manager

### PR DESCRIPTION
**Pull request by BenNottelling**
Reopening PR #910,  I was hoping to get feedback on the code before merging as this is my first time dealing with API functionality.
Also, I think we should resolve issue https://github.com/boxbilling/boxbilling/issues/922 before merging. If that is intended behavior, then I can update the server manager to ```throw new Server_Exception``` when something doesn't work. But the behavior I saw seems wrong

### CODE REVIEW

**Comment by BenNottelling** [comment]
We still falsely have a requirement to the old travis-ci integration @fordnox @timothygwebb

**Comment by BenNottelling** [comment]
I consider this ready for a review and then merge if nothing is brought up in the review

**Comment by timothygwebb** [comment]
> We still falsely have a requirement to the old travis-ci integration @fordnox @timothygwebb 

@BenNottelling This has been rectified.

**Comment by BenNottelling** [comment]
Does anybody have anything to comment on this or am I good to merge?

**Comment by timothygwebb** [comment]
Good to merge.

**Review by timothygwebb — APPROVED** [review]
RedBeanPHP Install to get your php8 working. https://www.redbeanphp.com/index.php?p=/install

**Comment by evrifaessa** [comment]
> RedBeanPHP Install to get your php8 working. https://www.redbeanphp.com/index.php?p=/install

Can we merge this to the source anyhow so everyone can use it?

**Comment by BenNottelling** [comment]
> Can we merge this to the source anyhow so everyone can use it?

Yes, we have RedBeanPHP here: https://github.com/boxbilling/boxbilling/blob/master/src/rb.php
It hasn't been updated since 2014

**Comment by evrifaessa** [comment]
> > Can we merge this to the source anyhow so everyone can use it?
> 
> Yes, we have RedBeanPHP here: https://github.com/boxbilling/boxbilling/blob/master/src/rb.php
> It hasn't been updated since 2014

ik, I was talking about updating it.

**Comment by timothygwebb** [comment]
@BenNottelling @evrifaessa There is a whole branch related to readbean https://github.com/boxbilling/boxbilling/tree/update/redbean

**Comment by evrifaessa** [comment]
> @BenNottelling @evrifaessa There is a whole branch related to readbean https://github.com/boxbilling/boxbilling/tree/update/redbean

It seems to be 400 commits behind the master branch. It would be good if someone works on it, because it seems like the only barrier between us and PHP 8.

**Pull request merged**
