### PR TITLE
Add extra customisation

### PR DESCRIPTION
**Pull request by givinghawk**
In this pull request I have added:
Custom header icons
✔Does not change between versions or during updates
✔Enable and disable options
image
image
Custom sidebar buttons
✔Does not change between versions or during updates
✔Enable and disable options
image
image
Custom favicon
✔Does not change between versions or during updates
✔Enable and disable options
image
image
Custom manage page buttons
✔Does not change between versions or during updates
✔Enable and disable options
image
image
In this pull request I have changed:
Sidebar note position
✔Does not change between versions or during updates
❌Enable and disable options
image

### CODE REVIEW

**Comment by givinghawk** [comment]
because of how i am saving the settings, it is not possible. i am using the same system that the footer links are using

**Comment by givinghawk** [comment]
I have added fontawesome v6, v5, v4 and v3 with a custom setting to this PR. 
image
✔Working on all themes
✔Saves between updates
✔Customisable

**Comment by givinghawk** [comment]
and i just fixed fontawesome v5 and v6 icons not working as they need `fa-brands` for example instead of just `fa`

**Comment by evrifaessa** [comment]
I'll post my detailed review probably later today.

**Comment by givinghawk** [comment]
> I'll post my detailed review probably later today.

thanks!

**Comment by evrifaessa** [comment]
Hello, thanks for the PR.

I couldn't understand why we're going to keep old Font Awesome versions though. v6 should have everything in the previous releases and of course even more than that. I'd also prefer a local copy to be the default instead of an external CDN.

Some discussion about this can be found in #978. I was also thinking of making Font Awesome a togglable module instead of loading it by default. We can also embed some more settings into that module.

We probably should discuss this more before merging anything. It shouldn't be easy to keep every theme compatible with every Font Awesome version, so we might need to select between different versions. Probably the newest one.

**Comment by givinghawk** [comment]
> Hello, thanks for the PR.
> 
> I couldn't understand why we're going to keep old Font Awesome versions though. v6 should have everything in the previous releases and of course even more than that. I'd also prefer a local copy to be the default instead of an external CDN.
> 
> Some discussion about this can be found in #978. I was also thinking of making Font Awesome a togglable module instead of loading it by default. We can also embed some more settings into that module.
> 
> We probably should discuss this more before merging anything. It shouldn't be easy to keep every theme compatible with every Font Awesome version, so we might need to select between different versions. Probably the newest one.

In response to fontawesome older versions, it is incase anyone wants to revert to the older looks of icons.
i can totally make them local and not on the cdn

**Comment by evrifaessa** [comment]
> In response to fontawesome older versions, it is incase anyone wants to revert to the older looks of icons. i can totally make them local and not on the cdn

I think that is an uncommon case and many people would rather go with the newer version that has everything from older ones. I'd personally prefer not to keep them in the codebase. Keeping four different major versions of Font Awesome bundled with BoxBilling might also increase storage usage by a little bit.

But for those who specifically need an old version, they can always import custom CSS.

**Comment by givinghawk** [comment]
if you want i can remove the fontawesome parts of this pr for now?

**Comment by givinghawk** [comment]
i will remove the fontawesome related things from the pr

**Comment by evrifaessa** [comment]
It's not just drop v4 and import v6. Please remove anything related to Font Awesome and let me handle it in another PR. Thanks.

**Comment by givinghawk** [comment]
> It's not just drop v4 and import v6. Please remove anything related to Font Awesome and let me handle it in another PR. Thanks.

done

**Comment by John-S4** [comment]
The ability to add custom favicon, menu items, and sidebar items is very useful, preventing the need to hack about theme files on a per install basis, and this seems to be well implemented, I can't see any issues with it. 

FWIW I agree with @evrifaessa that there is no reason to support old versions of Font Awesome, it's just adding unnecessary complexity. If somebody is that picky about wanting and older version of an icon then they can find their own way around it.

**Comment by timothygwebb** [comment]
@givinghawk This branch has conflicts that must be resolved
 Use the command line  to resolve conflicts before continuing.
Conflicting files
src/bb-themes/bootstrap/config/settings.html
src/bb-themes/bootstrap/html/layout_default.phtml
src/bb-themes/bootstrap/html/mod_order_manage.phtml
src/bb-themes/bootstrap/html/partial_menu.phtml

**Pull request closed without merging**
