### PR TITLE
Fixed Service.php when I pulled from master crashed my system due to …

### PR DESCRIPTION
**Pull request by timothygwebb**
…the passing from Model_ServiceHosting to Model_ServiceHostingServer

### CODE REVIEW

**Review by fordnox — APPROVED** [review]

**Comment by samapraku** [comment]
@timothygwebb it appears you introduced all those changes in your previous commits that is  causing the issue you have mentioned. The Service.php file didn't have any issues and worked alright prior to that. 
Check the History: 
https://github.com/boxbilling/boxbilling/commits/df141caed467330cf76cf84a669ab12931f05692/src/bb-modules/Servicehosting/Service.php

I suggest you revert the file to the last stable commit https://github.com/boxbilling/boxbilling/commit/e64244ff6bf0ef8fc345d36449fb24bfc490cdcb 

That way it will be easier to identify and fix any issues that were introduced.

**Comment by samapraku** [comment]
@fordnox @timothygwebb this should not be merged yet.
I have compared the current state of the file with the last working commit https://github.com/boxbilling/boxbilling/commit/e64244ff6bf0ef8fc345d36449fb24bfc490cdcb and the file still has a lot of changes which I suspect will not make it work properly.

It should be reverted to last working state and any new features that depend on it should be rewritten to work with the file as it will break a lot of things.

**Comment by samapraku** [comment]
@fordnox  Below is the unit test result for the ServiceHosting module for this pull request

```console

@user /e/GitHub/PHP/boxbilling-master (Service)
$ src/bb-vendor/bin/phpunit ./tests/bb-modules/Servicehosting/
PHPUnit 9.4.2 by Sebastian Bergmann and contributors.

.............EEEE..............................................E. 65 / 88 ( 73%)
.....EEEFFE.......EEE..                                           88 / 88 (100%)

Time: 00:01.427, Memory: 12.00 MB

There were 12 errors:

1) Box\Mod\Servicehosting\Api\AdminTest::testserver_get
TypeError: Argument 1 passed to Mock_Service_7f1f218a::toHostingServerApiArray() must be an instance of Model_ServiceHosting, instance of Model_ServiceHostingServer given, called in E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Api\Admin.php on line 228

E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Api\Admin.php:228
E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\Api\AdminTest.php:325

2) Box\Mod\Servicehosting\Api\AdminTest::testserver_delete
TypeError: Argument 1 passed to Mock_Service_7f1f218a::deleteServer() must be an instance of Model_ServiceHosting, instance of Model_ServiceHostingServer given, called in E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Api\Admin.php on line 246

E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Api\Admin.php:246
E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\Api\AdminTest.php:356

3) Box\Mod\Servicehosting\Api\AdminTest::testserver_update
TypeError: Argument 1 passed to Mock_Service_7f1f218a::updateServer() must be an instance of Model_ServiceHosting, instance of Model_ServiceHostingServer given, called in E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Api\Admin.php on line 278

E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Api\Admin.php:278
E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\Api\AdminTest.php:386

4) Box\Mod\Servicehosting\Api\AdminTest::testserver_test_connection
TypeError: Argument 1 passed to Mock_Service_7f1f218a::testConnection() must be an instance of Model_ServiceHosting, instance of Model_ServiceHostingServer given, called in E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Api\Admin.php on line 298

E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Api\Admin.php:298
E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\Api\AdminTest.php:416

5) Box\Mod\Servicehosting\ServiceTest::testtoApiArray
TypeError: Argument 1 passed to Box\Mod\Servicehosting\Service::toHostingServerApiArray() must be an instance of Model_ServiceHosting, instance of Model_ServiceHostingServer given, called in E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Service.php on line 449

E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Service.php:465
E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Service.php:449
E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php:811

6) Box\Mod\Servicehosting\ServiceTest::testdeleteServer
TypeError: Argument 1 passed to Box\Mod\Servicehosting\Service::deleteServer() must be an instance of Model_ServiceHosting, instance of Model_ServiceHostingServer given, called in E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php on line 942

E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Service.php:655
E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php:942

7) Box\Mod\Servicehosting\ServiceTest::testupdateServer
TypeError: Argument 1 passed to Box\Mod\Servicehosting\Service::updateServer() must be an instance of Model_ServiceHosting, instance of Model_ServiceHostingServer given, called in E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php on line 982

E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Service.php:663
E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php:982

8) Box\Mod\Servicehosting\ServiceTest::testgetServerManager
TypeError: Argument 1 passed to Box\Mod\Servicehosting\Service::getServerManager() must be an instance of Model_ServiceHosting, instance of Model_ServiceHostingServer given, called in E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php on line 1000

E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Service.php:699
E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php:1000

9) Box\Mod\Servicehosting\ServiceTest::testtestConnection
TypeError: Argument 1 passed to Box\Mod\Servicehosting\Service::testConnection() must be an instance of Model_ServiceHosting, instance of Model_ServiceHostingServer given, called in E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php on line 1048

E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Service.php:723
E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php:1048

10) Box\Mod\Servicehosting\ServiceTest::testgetServerManagerWithLog
TypeError: Argument 1 passed to Box\Mod\Servicehosting\Service::getServerManagerWithLog() must be an instance of Model_ServiceHosting, instance of Model_ServiceHostingServer given, called in E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php on line 1220

E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Service.php:874
E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php:1220

11) Box\Mod\Servicehosting\ServiceTest::testgetMangerUrls
Error: Call to undefined method Mock_Service_22a04a24::getMangerUrls()

E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php:1245

12) Box\Mod\Servicehosting\ServiceTest::testgetMangerUrlsException
Error: Call to undefined method Mock_Service_22a04a24::getMangerUrls()

E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php:1264

--

There were 2 failures:

1) Box\Mod\Servicehosting\ServiceTest::testgetServerManagerManagerNotDefined
Failed asserting that exception of type "TypeError" matches expected exception "Box_Exception". Message was: "Argument 1 passed to Box\Mod\Servicehosting\Service::getServerManager() must be an instance of Model_ServiceHosting, instance of Model_ServiceHostingServer given, called in E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php on line 1012" at
E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Service.php:699
E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php:1012
.

2) Box\Mod\Servicehosting\ServiceTest::testgetServerManagerServerManagerInvalid
Failed asserting that exception of type "TypeError" matches expected exception "Box_Exception". Message was: "Argument 1 passed to Box\Mod\Servicehosting\Service::getServerManager() must be an instance of Model_ServiceHosting, instance of Model_ServiceHostingServer given, called in E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php on line 1029" at
E:\GitHub\PHP\boxbilling-master\src\bb-modules\Servicehosting\Service.php:699
E:\GitHub\PHP\boxbilling-master\tests\bb-modules\Servicehosting\ServiceTest.php:1029
.

ERRORS!
Tests: 88, Assertions: 242, Errors: 12, Failures: 2.



```

**Comment by timothygwebb** [comment]
@samapraku This was my final unit test.

webmaster@webbhostingservices:~/httpdocs/boxbilling$ src/bb-vendor/bin/phpunit ./tests/bb-modules/Servicehosting/
PHPUnit 9.4.2 by Sebastian Bergmann and contributors.

................................................................. 65 / 88 ( 73%)
.......................                                           88 / 88 (100%)

Time: 00:00.105, Memory: 6.00 MB

OK (88 tests, 288 assertions)

**Comment by fordnox** [comment]
unit test shiuld be run on each pull request with travis-ci or github actions

**Comment by timothygwebb** [comment]
Yes, I normally do unit testing with github actions. But it seems that the
project location of the composer.json and lock files are giving me errors
on my php.yml file. The object is wanting to have it in the root folder not
in the src folder. I am working on a way around this currently but that is
not a high priority for me right now. I have been using the travis ci and
working with @samapraku <https://github.com/samapraku> doing unit testing
on my pull request because we were having different results using travis
ci. What is in the pull request has no errors in travis ci.

**Comment by timothygwebb** [comment]
@samapraku If you are good now with these changes I will merge this edit. @fordnox has approved the changes.

**Comment by samapraku** [comment]
@timothygwebb please merge this pull request as it is causing my pull request https://github.com/boxbilling/boxbilling/pull/695 for the unit tests to fail.

**Comment by timothygwebb** [comment]
@samapraku  I have merged the request.

**Pull request merged**
