### PR TITLE
Organise Asset folder structure in BoxBilling Theme

### PR DESCRIPTION
**Pull request by rndevuk**
Organise Asset folder structure in BoxBilling Theme to match the file structure of the Huraga theme for consistancy

### CODE REVIEW

**Comment by fordnox** [comment]
what is the value of this change?

**Comment by rndevuk** [comment]
Consistency across themes is the main reason. but secondary is that i will be submitting a feature that enables live compiling of scss. so having a common directory structure accross themes makes that work better.

**Comment by timothygwebb** [comment]
@rndevuk @fordnox Are you going to submitting a pull request that implements the following https://github.com/sass/sass?

**Comment by rndevuk** [comment]
@timothygwebb no

**Comment by timothygwebb** [comment]
> @timothygwebb no

@rndevuk I wonder if what you are doing could be related to the tfpdf Item that I was working on. Could it be possible to integrate that solution into this one since it is in relation to layout and css. Would you like to take the tfpdf issue?

**Comment by rndevuk** [comment]
tfpdf doesnt use stylesheets though.. as far as i know. tfpdf  is suppose to use inline css?

**Comment by timothygwebb** [comment]
> tfpdf doesnt use stylesheets though.. as far as i know. tfpdf is suppose to use inline css?

@rndevuk I was thinking of completely refactoring how the PDF's are done and using [](https://github.com/tecnickcom/tcpdf) which does use style sheets. Here is an example [](https://tcpdf.org/examples/example_061/)

**Comment by rndevuk** [comment]
Once you have gotten that done. the work i do would be simple enought to implement. I will be using https://github.com/scssphp/scssphp to compile the scss. are you planning on using twig to compile the html template for tcpdf?

**Comment by timothygwebb** [comment]
@rndevuk It would make since to since you can set different compilers in Twig.

**Comment by rndevuk** [comment]
does this pr have the go approval?

**Comment by timothygwebb** [comment]
> does this pr have the go approval?

@fordnox I will merge this request if you are fine with the restructuring of the folder structure I am and it makes since if our discussion on the future of integration of scss.

**Comment by fordnox** [comment]
if the tests are passing then we can merge

**Pull request merged**
