### PR TITLE
Using HTML `<img>` tag when render icon_url

### PR DESCRIPTION
**Pull request by noobpk**
Fix bug stored xss in icon_url
Disclosure: https://huntr.dev/bounties/e7ae5152-2997-461b-a783-c942a12589c2/

### CODE REVIEW

**Comment by evrifaessa** [comment]
This isn't a complete solution. We still have the `img_tag` filter:

https://github.com/boxbilling/boxbilling/blob/6cc85ddbbc66b1c7bf369e6d5aca47f9d9a688da/src/bb-library/Box/TwigExtensions.php#L181-L186

Why don't we just fix the filter instead of going back to plain HTML?

**Comment by noobpk** [comment]
> This isn't a complete solution. We still have the `img_tag` filter:
> 
> https://github.com/boxbilling/boxbilling/blob/6cc85ddbbc66b1c7bf369e6d5aca47f9d9a688da/src/bb-library/Box/TwigExtensions.php#L181-L186
> 
> Why don't we just fix the filter instead of going back to plain HTML?

Well, I know that
Because I see you used `` tag for addon icon_url
https://github.com/boxbilling/boxbilling/blob/6fa9a6e5d3747b58e885b8dd1ff33410513a70fe/src/bb-modules/Orderbutton/html_client/mod_orderbutton_addons.phtml#L20

I will try to find a workaround for `img_tag` and update this PR

**Comment by noobpk** [comment]
@evrifaessa I fixed the bug by adding `htmlspecialchars` to `twig_img_tag` . Can you confirm it's valid?

**Comment by BenNottelling** [comment]
I'm not sure if htmlspecialchar is the best way to handle this?
image
 
 It converts special characters into HTML entities. Can someone else provide input on this?
 @evrifaessa

**Review by BenNottelling — APPROVED** [review]
It looks like we used the same solution for another vulnerability:
https://github.com/boxbilling/boxbilling/commit/47a32ea3014a589fef512bc5089867c7b2e3ee16

Thanks for the patch, I'll go accept it on huntr.dev

**Pull request merged**
