### PR TITLE
Update syntax to PSR12 coding standards

### PR DESCRIPTION
**Pull request by andpavlenko**
- Added .editorconfig which is supported by all modern IDE
- Changes php_codesniffer to PHP CS Fixer with best practice rules
- #1236 - Migrate to PSR12 coding standards. Fixed only syntax without risky rules and breaking changes
- #1239 - Update composer stability to stable
- #1240 - Bump to PHP 8.0 in composer.json
- #1239 - Sync composer.lock with stable packages
- Remove guzzle/guzzle v3.9 as very old and unused

### CODE REVIEW

**Comment by BenNottelling** [comment]
I'm all for updating to PSR12 standards, but I'm not merging this until all the checks pass
If they pass because we decide to drop PHP 7.4 like in https://github.com/boxbilling/boxbilling/issues/1240 that's good by me, otherwise the composer json and lock file will need to be updated to get everything passing correctly

PS: Thanks for the PR :)

**Comment by andpavlenko** [comment]
@BenNottelling I'l be waiting decision by issue #1240.

**Review by BenNottelling — CHANGES_REQUESTED** [review]
Where did these additional files from?
src/bb-library/font/unifont/

**Comment by andpavlenko** [comment]
> Where did these additional files from? src/bb-library/font/unifont/

I will check this.

**Comment by fordnox** [comment]
Greate PR, happy about it.

**Comment by timothygwebb** [comment]
That makes two of us. I am glad we are moving forward and communicating as a team. Keep up the great work and let me know if you all need anything.  Sent from Mail for Windows From: Andrius PutnaSent: Friday, April 1, 2022 6:02 AMTo: boxbilling/boxbillingCc: SubscribedSubject: Re: [boxbilling/boxbilling] Update syntax to PSR12 coding standards (PR #1237) Great PR, happy about it.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by andpavlenko** [comment]
@fordnox @timothygwebb I'll wait for merge and start to next... ;)

**Review by evrifaessa — APPROVED** [review]
Haven't tested but it's mostly a cosmetic change. I think it's good to go.

**Pull request merged**
