### PR TITLE
Coinbase Adapter and DotTK Fix

### PR DESCRIPTION
**Pull request by jebwizoscar**
Coinbase Adapter and DotTK Fix

### CODE REVIEW

**Comment by fordnox** [comment]
Thank you for this contribution. 
Please open same pull request on extensions https://github.com/boxbilling/extensions repository instead of master

**Comment by jebwizoscar** [comment]
@fordnox but for DotTK it's a fix, should I pull the fix here?

**Comment by 4Giedrius** [comment]
@jebwizoscar DotTK support will be dropped in next major release of BoxBilling, this adapter was moved  to [extensions](https://github.com/boxbilling/extensions) repository. Please open pull request there.

**Comment by jebwizoscar** [comment]
@4Giedrius opened :)

**Pull request closed without merging**
