### PR TITLE
[DON'T MERGE] Rev42/tfpdf

### PR DESCRIPTION
**Pull request by timothygwebb**

### CODE REVIEW

**Comment by evrifaessa** [comment]
@timothygwebb, none of the PDF functions still works, however.

This one returns "Class 'TFPDF' not found":

https://github.com/boxbilling/boxbilling/blob/083d97aa3b97890e3fe3b18648b677c63f95e5d4/src/bb-library/PDF_ImageAlpha.php#L4

**Comment by timothygwebb** [comment]
> @timothygwebb, none of the PDF functions still works, however.
> 
> This one returns "Class 'TFPDF' not found":
> 
> https://github.com/boxbilling/boxbilling/blob/083d97aa3b97890e3fe3b18648b677c63f95e5d4/src/bb-library/PDF_ImageAlpha.php#L4

class PDF_ImageAlpha extends PDF

**Comment by evrifaessa** [comment]
Still returns errors, "Fatal error: Cannot declare class tFPDF\PDF, because the name is already in use in .\bb-library\PDF.php on line 9"

**Comment by evrifaessa** [comment]
Now, there is another problem.

```
Warning: stat(): stat failed for C:\xampp\htdocs\bb-library/../font/unifont/DejaVuSansCondensed.ttf in C:\xampp\htdocs\bb-library\PDF_ImageAlpha.php on line 1042
```

```
Can't open file C:\xampp\htdocs\bb-library/../font/unifont/DejaVuSansCondensed.ttf

Class: "RuntimeException"

File: "C:\xampp\htdocs\bb-vendor\docnet\tfpdf\src\tFPDF\TTFontFile.php"

Line: "61"

Trace:
#0 C:\xampp\htdocs\bb-library\PDF_ImageAlpha.php(1053): tFPDF\TTFontFile->getMetrics('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\bb-modules\Invoice\Service.php(1196): tFPDF\PDF->AddFont('dejavu', '', 'DejaVuSansConde...', true)
#2 C:\xampp\htdocs\bb-modules\Invoice\Api\Guest.php(135): Box\Mod\Invoice\Service->generatePDF('0af9950ab6948b8...', Object(Model_Guest))
#3 C:\xampp\htdocs\bb-library\Api\Handler.php(112): Box\Mod\Invoice\Api\Guest->pdf(Array)
#4 C:\xampp\htdocs\bb-modules\Invoice\Controller\Client.php(106): Api_Handler->__call('invoice_pdf', Array)
#5 [internal function]: Box\Mod\Invoice\Controller\Client->get_pdf(Object(Box_AppClient), '0af9950ab6948b8...')
#6 C:\xampp\htdocs\bb-library\Box\App.php(199): ReflectionMethod->invokeArgs(Object(Box\Mod\Invoice\Controller\Client), Array)
#7 C:\xampp\htdocs\bb-library\Box\App.php(249): Box_App->executeShared('Box\\Mod\\Invoice...', 'get_pdf', Array)
#8 C:\xampp\htdocs\bb-library\Box\App.php(143): Box_App->processRequest()
#9 C:\xampp\htdocs\index.php(27): Box_App->run()
#10 {main}
```

**Review by timothygwebb — COMMENTED** [review]
Looks like that should do it I am really tired and I am going to bed its 3:13 am and I am trying to knock this stuff out. thanks for all your help. Keep up the great work.

**Comment by evrifaessa** [comment]
This is still in progress, please don't merge it yet.

**Comment by timothygwebb** [comment]
> This is still in progress, please don't merge it yet.

Thanks for the great review if you see anything else and modify it go ahead and finish the process. I have it now to where it will be resolvable with all the pieces including the needed .ttf files.

**Comment by timothygwebb** [comment]
> > This is still in progress, please don't merge it yet.
> 
> Thanks for the great review if you see anything else and modify it go ahead and finish the process. I have it now to where it will be resolvable with all the pieces including the needed .ttf files.

I drafted the pull request just an FYI.

**Comment by evrifaessa** [comment]
Just FYI, this PDF script doesn't seem to go well with PHP 7.4..

https://www.php.net/manual/de/migration74.incompatible.php#migration74.incompatible.core.non-array-access

`Notice: Trying to access array offset on value of type int in C:\...\bb-library\PDF_ImageAlpha.php on line 3055`

**Comment by timothygwebb** [comment]
> Just FYI, this PDF script doesn't seem to go well with PHP 7.4..
> 
> https://www.php.net/manual/de/migration74.incompatible.php#migration74.incompatible.core.non-array-access
> 
> `Notice: Trying to access array offset on value of type int in C:\...\bb-library\PDF_ImageAlpha.php on line 3055`

I have heard mention of this before something about the di and logging.

**Comment by timothygwebb** [comment]
> > Just FYI, this PDF script doesn't seem to go well with PHP 7.4..
> > https://www.php.net/manual/de/migration74.incompatible.php#migration74.incompatible.core.non-array-access
> > `Notice: Trying to access array offset on value of type int in C:\...\bb-library\PDF_ImageAlpha.php on line 3055`
> 
> I have heard mention of this before something about the di and logging.

Ask @samapraku  if you need assistance I think I remember him making the comment.

**Comment by evrifaessa** [comment]
> > > Just FYI, this PDF script doesn't seem to go well with PHP 7.4..
> > > https://www.php.net/manual/de/migration74.incompatible.php#migration74.incompatible.core.non-array-access
> > > `Notice: Trying to access array offset on value of type int in C:\...\bb-library\PDF_ImageAlpha.php on line 3055`
> > 
> > 
> > I have heard mention of this before something about the di and logging.
> 
> Ask @samapraku if you need assistance I think I remember him making the comment.

It'd be cool if someone else can fix it, watching TV series right now..

**Comment by timothygwebb** [comment]
> > > > Just FYI, this PDF script doesn't seem to go well with PHP 7.4..
> > > > https://www.php.net/manual/de/migration74.incompatible.php#migration74.incompatible.core.non-array-access
> > > > `Notice: Trying to access array offset on value of type int in C:\...\bb-library\PDF_ImageAlpha.php on line 3055`
> > > 
> > > 
> > > I have heard mention of this before something about the di and logging.
> > 
> > 
> > Ask @samapraku if you need assistance I think I remember him making the comment.
> 
> It'd be cool if someone else can fix it, watching TV series right now..

@evrifaessa That is fine it doesn't have to be done right now it was the only time I had to work on it to get it to where some one else could pick it up and run with it. Goodnight and have a great rest of your day. Until next time. 👍🏻

**Pull request closed without merging**
