### PR TITLE
for Vesta control panel

### PR DESCRIPTION
**Pull request by robin-bd**
this will able to manage vesta cp

### CODE REVIEW

**Comment by BenNottelling** [comment]
Why doesn't this have a file ext?
Same goes for the other PR

**Comment by gOOvER** [comment]
i would like to see, when you adopt this to hestiacp too. Hestiacp is a for of Vesta and is  more under active development than VestaCP

**Comment by gOOvER** [comment]
One of the Devs created allready some Servermodules for Boxbilling

https://github.com/jaapmarcus/boxbilling-hestia

**Comment by jaapmarcus** [comment]
"PR" has been resolved with 

https://github.com/boxbilling/boxbilling/pull/1256

This one can be closed...

**Pull request closed without merging**
