### PR TITLE
Add balance pane (whmcs feature)

### PR DESCRIPTION
**Pull request by givinghawk**
In WHMCS
image
In BoxBilling
image
image

✔Saves between updates
✔Works with different themes
✔Toggleable

### CODE REVIEW

**Comment by andpavlenko** [comment]
@givinghawk Sync your local master with upstream master at first.

**Comment by givinghawk** [comment]
> @givinghawk Sync your local master with upstream master at first.

what do you mean? include the bump to twig 3 commit?

**Comment by evrifaessa** [comment]
> @givinghawk Sync your local master with upstream master at first.

No worries. Merging can still be done automatically. We should wait for reviews first though.

**Comment by andpavlenko** [comment]
Look at PR #1275 this [comment](https://github.com/boxbilling/boxbilling/pull/1275#issuecomment-1102409927).

**Comment by givinghawk** [comment]
that balance pane was meant to be in the sidebar, looking the exact same as whmcs @andpavlenko...

**Comment by andpavlenko** [comment]
This worst for responsive design. Sidebar hidden on small devices!
Why copy someone else's, when you can do better? ;)

**Comment by timothygwebb** [comment]
@givinghawk This branch has conflicts that must be resolved.

**Review by timothygwebb — CHANGES_REQUESTED** [review]
@givinghawk This branch has conflicts that must be resolved

**Pull request closed without merging**
