### PR TITLE
Updated composer dependencies

### PR DESCRIPTION
**Pull request by timothygwebb**
Updated composer for dependencies.

### CODE REVIEW

**Comment by evrifaessa** [comment]
Any benefits or special reasons to start using unstable branches?

**Comment by timothygwebb** [comment]
> Any benefits or special reasons to start using unstable branches?

None that I know of but I know why there are development branches showing up and it is a simple resolution in which we all should have a larger discussion around and that is the truly identifiable way to guarantee a stable branch. 

The code below in composer.json is why there are development branches in use

{
    "name": "boxbilling/boxbilling",
    "description": "Open Source Billing Software",
    "version": "4.22.0-beta.2",
    "readme": "https://github.com/boxbilling/boxbilling/blob/master/README.md",
  ###   **"minimum-stability": "dev",**
    "type": "project",
    "license": "Apache-2.0",
    "keywords": ["billing", "invoice", "client management"],
    "homepage": "https://www.boxbilling.org",
    "authors": [
        {
            "name": "Andrius Putna",
            "email": "andrius@boxbilling.com"
        }
    ],


What should we identify the master branch current minimum stability as?

From what you are discussing it should be stable but in turn I have heard communications that the master branch should not be used in production environments and at this time is not considered stable. 

So in regards to that please correctly identify the state of the master branch and define it in the section called minimum stability. 

This in turn will only allow stable branches to be used unless manually flagged individually.

For definition of what minimum stability is please see below.

minimum-stability

This defines the default behavior for filtering packages by stability. This defaults to stable, so if you rely on a dev package, you should specify it in your file to avoid surprises.

All versions of each package are checked for stability, and those that are less stable than the minimum-stability setting will be ignored when resolving your project dependencies. (Note that you can also specify stability requirements on a per-package basis using stability flags in the version constraints that you specify in a require block (see package links for more details).

Available options (in order of stability) are dev, alpha, beta, RC, and stable.

**Comment by BenNottelling** [comment]
No, the only time I am okay with using dev or unstable branches is if we had a bleeding edge branch for experimental features.
We really should be moving the composer config to be "stable" instead of dev if at all possible

**Comment by timothygwebb** [comment]
@BenNottelling Would you like to create a bleeding edge branch?

**Comment by BenNottelling** [comment]
> @BenNottelling Would you like to create a bleeding edge branch?

Honestly, no
We don't have enough manpower & work being put into BB to justify it

**Comment by timothygwebb** [comment]
@BenNottelling Thanks for your response. When the community would like to discuss this please be sure to include me.

**Comment by andpavlenko** [comment]
Minimum stability 'dev' make sense if you work on features from dev (unstable) libraries included in your main project. Maybe testing it at whole complex project, etc...

I'm surprised that the issue of stability is debatable here.  ((

**Comment by BenNottelling** [comment]
There are some long running issues with code quality from previous contributors, some of which has been resolved, some of it hasn't

**Comment by andpavlenko** [comment]
@BenNottelling, minimum-stability=dev it's about projects included in your application, but not about main project. In other words: if some other project want to use your master (unstable) branch they set minimum-stability=dev in them composer.json.

Stability of your main project depend only at release circle of you project.

**Comment by BenNottelling** [comment]
@andpavlenko 
I am aware of that.
However, BoxBilling using unstable or dev packages in release builds is something that I would consider to be a quality issue with BoxBilling

**Comment by andpavlenko** [comment]
@BenNottelling, let's say I'm still poorly aware of the Boxbilling code. Show me please reference of code that makes it impossible to use the stable version in composer.

**Comment by evrifaessa** [comment]
Obsolete now, check #1237.

**Pull request closed without merging**
