### PR TITLE
Remove license check!

### PR DESCRIPTION
**Pull request by Dylan3304**
Since this is open source, why do you still have license validation? I removed it for you so you don't have to!

### CODE REVIEW

**Comment by 2braincells2go** [comment]
I was getting ready to merge, but see:

 Failed — 1 successful and 1 failing checks
Details continuous-integration/travis-ci/pr

**Comment by Dylan3304** [comment]
Do you mind showing me the failing check?

**Comment by 2braincells2go** [comment]
I see it in this tread. Here is a screenshot:

github-0004506

**Comment by vaidas-lungis** [comment]
“Free software” means software that respects users' freedom and community. Roughly, it means that the users have the freedom to run, copy, distribute, study, change and improve the software. Thus, “free software” is a matter of liberty, not price. To understand the concept, you should think of “free” as in “free speech,” not as in “free beer”.

**Comment by gOOvER** [comment]
Then don't release it und an OpenSource License.

I bet your plans are,  to offer an Pro Version again in Future. Am i right?

**Comment by vaidas-lungis** [comment]
BoxBilling is under an [Apache License](https://github.com/boxbilling/boxbilling/blob/master/LICENSE) You can read more on licenses here: http://choosealicense.com/licenses/

We have been offering free and pro license plans for clients as you can see it here http://www.boxbilling.com/order

**Comment by lifehome** [comment]
It would be better for changing `bb-library/Box/License.php` Line 75 to this:  
````
($bb_license) ? return \Box_Version::TYPE_PRO : return \Box_Version::TYPE_FREE;
````

This way, people will use the license field more often.

**Comment by Dylan3304** [comment]
I then realized that, https://gist.github.com/Dylan3304/014149939b7a8354fa6e

**Comment by fossxplorer** [comment]
Does Apache license set any limitations of usage of a software?

**Comment by gOOvER** [comment]
No it don't..... You can do what ever you want the the Code, as long as you respect Copyright ;)

https://www.apache.org/licenses/LICENSE-2.0

You can remove licence Check, when this was your question ;)

**Comment by fossxplorer** [comment]
@gOOvER 
Ok, that was my understanding too after briefly reading the Apache license. And yes, in order to use BoxBilling instead of WHMCS, i need to know that there are no limitations and a way to remove the license check. I assume this PR code can remove it?

**Comment by lifehome** [comment]
@fossxplorer If you intend to do this, then modify the function as the PR, it is your freedom to do anything, but once you changed this AND WITHOUT respecting the Apache license(quote from @vaidas-lungis), this place will and/or might not welcome your further questions.

**Comment by gOOvER** [comment]
I'm not a psrt of the Team... :) I only answer your question :D.... I think, they don't really know what they do, when they set the Licence too Apache Licence...

And the explanation of "vaidas-lungis"

"“Free software” means software that respects users' freedom and community. Roughly, it means that the users have the freedom to run, copy, distribute, study, change and improve the software. Thus, “free software” is a matter of liberty, not price. To understand the concept, you should think of “free” as in “free speech,” not as in “free beer”."

is totally wrong....... I think, he don't really know what he talking about ;) In my eye#s they want free Developers and offer then this Version as a Premium ^^^

**Comment by gOOvER** [comment]
@lifehome: He only need to tell the Copyright Holder.. ot more... he can do what he want whit the Code ;)

**Comment by tiduswz** [comment]
"A license defines the rights and obligations that a licensor grants to a licensee. Open source licenses grant licensees the right to copy, modify and redistribute source code (or content). These licenses may also impose obligations (e.g., modifications to the code that are distributed must be made available in source code form, an author attribution must be placed in a program/ documentation using that open source).

Authors initially derive a right to grant a license to their work based on the legal theory that upon creation of a work the author owns the copyright in that work. What the author/licensor is granting when they grant a license to copy, modify and redistribute their work is the right to use the author's copyrights. The author still retains ownership of those copyrights, the licensee simply is allowed to use those rights, as granted in the license, so long as they maintain the obligations of the license. The author does have the option to sell/assign, versus license, their exclusive right to the copyrights to their work; whereupon the new owner/assignee controls the copyrights. The ownership of the copyright (the "rights") is separate and distinct from the ownership of the work (the "thing") – a person can own a copy of a piece of code (or a copy of a book) without the rights to copy, modify or redistribute copies of it."

More info @ http://en.wikipedia.org/wiki/Open-source_software

**Pull request closed without merging**
