### PR TITLE
Removed links to the dead forum of ours

### PR DESCRIPTION
**Pull request by evrifaessa**
This PR will remove links to the dead forum [(it used to be here)](https://boxbilling.com/forum). Nobody moderates it and we now have GitHub Discussions and Issues instead.

I'd still love to hear some thoughts of yours. Have a nice day.

### CODE REVIEW

**Comment by BenNottelling** [comment]
You updated the copyright text on the installer, but left the old URL.

Also, maybe it would be good to go through and try to update all old URLs in one PR?

**Comment by evrifaessa** [comment]
> You updated the copyright text on the installer, but left the old URL.
No?

**Comment by BenNottelling** [comment]
> No?

I think yes lol
image

**Comment by evrifaessa** [comment]
> I think yes lol

Oh, this one... Once Andrius gets back to the project, I'll ask him to grant us access to the source of .com.

**Comment by BenNottelling** [comment]
> Oh, this one... Once Andrius gets back to the project, I'll ask him to grant us access to the source of .com.

That's fine, but since we don't know how long it'll be until that happens I think it would be best practice to keep URLs directed at our github

**Comment by John-S4** [comment]
It's not just that nobody moderates that forum, but that it seems to be locked completely and even if you are logged in it is not possible to post there. 

Good that it is removed. 

Also agree that at this moment links to the .com website would be much better pointed at the .org website. At least the information there is not just wrong and misleading.

**Comment by evrifaessa** [comment]
I merged this. We'll see what we can do about the main website later.

**Pull request merged**
