### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by S4-Hosting**
Added Discord link to support section

### CODE REVIEW

**Comment by evrifaessa** [comment]
the discord server is an unofficial one, so I doubt we should add it to README.

**Comment by timothygwebb** [comment]
@S4-Hosting @evrifaessa So is this a go or no go. Official or not it does seem to be the location everyone is migrating to.

**Comment by S4-Hosting** [comment]
In my opinion the Discord server and github are the only valid places that are listed there. 

The website is out of date, the documentation needs to be seriously updated, the Twitter account last posted 8 years ago and the Facebook account last posted 5 years ago. 

Anyone following links to those social media accounts will clearly believe the project is dead. The Discord server on the other hand actually works, official or not, and if this is truly a community driven project then surely the place where that community are interacting should be listed. 

We can add the word 'unofficial' if you like, but I thought the word 'community' that I used already kind of covered it.

**Comment by timothygwebb** [comment]
@S4-Hosting @evrifaessa Just letting you know that I have build the Github Page off of the /docs directory and integrated with jekyl. http://boxbilling.github.io/boxbilling/ for your reference the documentation if you would like to continue down this path as well. https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Pull request merged**
