### PR TITLE
Composer.json and composer.lock update

### PR DESCRIPTION
**Pull request by timothygwebb**
/httpdocs/boxbilling/src	1 VULNERABLE PACKAGES
Vulnerable packages
Version
Affected versions
Description

squizlabs/php_codesniffer
DEV
1.5.6

>=1.0.0 - <2.0.0

Arbitrary shell execution

Details

https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/2.8.1

### CODE REVIEW

**Review by evrifaessa — APPROVED** [review]

**Comment by evrifaessa** [comment]
@fordnox, could you check this, and merge if possible? travis didn't respond for some reason.

**Comment by timothygwebb** [comment]
@evrifaessa I cant figure out why travis is not picking this up. Maybe @fordnox  can. I have re-ran the tests trying to get it to pickup on travis and it does not seem to be doing so. I will continue to try other things to see if I can get travis to pick it back up again.

**Comment by timothygwebb** [comment]
@evrifaessa @fordnox https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154/9

**Comment by evrifaessa** [comment]
@timothygwebb, can you close this pull request, and try to commit what you changed in here again? Creating a new PR will trigger Travis and get it running again, I guess..

**Comment by evrifaessa** [comment]
Check #751

**Pull request closed without merging**
