### PR TITLE
PHP 7.4 Compatibility Update

### PR DESCRIPTION
**Pull request by rndevuk**
Think this should cover #644

### CODE REVIEW

**Comment by rndevuk** [comment]
don't merge this yet. there are more that instances of this that need to replace

**Comment by timothygwebb** [comment]
@rndevuk Thank you for marking this as draft. I understand the purpose of shelving and drafting. Let me know when you want this merged.

**Comment by timothygwebb** [comment]
@rndevuk By the way I know there are a lot more changes and I actually have them all listed in the following issue. https://github.com/boxbilling/boxbilling/pull/623#issuecomment-683875823

**Comment by rndevuk** [comment]
Thanks @timothygwebb it should be ready in a few days

**Comment by timothygwebb** [comment]
@rndevuk https://github.com/boxbilling/boxbilling/issues/644#issuecomment-691696551

**Comment by rndevuk** [comment]
Deprecated: Function create_function() is deprecated in /home/fdgt/public_html/boxbilling/bb-library/Box/BeanHelper.php on line 60 #585
Deprecated: Function create_function() is deprecated in /home/fdgt/public_html/boxbilling/bb-library/Box/BeanHelper.php on line 60 #585

seems like these one's were fixed in a prior PR.

**Comment by rndevuk** [comment]
>Error: Trying to access array offset on value of type null in ~\bb-library\Box\Log.php 123 #638

seems to have been fixed by PR #639

**Comment by rndevuk** [comment]
Having looked at tfpdf and guzzle, i will update them in a seperate PR.

Boxbilling will still work on php 7.4 without updating  tfpdf and guzzle so this PR should be good to go. I think.

**Review by samapraku — APPROVED** [review]

**Comment by timothygwebb** [comment]
The changes have been merged into the development branch. I will confirm with @fordnox about merging into the master branch. I would like for him to make the release and merge into the master. I will request his review upon the addition of guzzle and pdf changes to the development branch.

**Pull request merged**
