### PR TITLE
[WIP] Porting Bootstrap 3.x. to the latest 5.x.

### PR DESCRIPTION
**Pull request by evrifaessa**
In this branch, I'm attempting to migrate our Bootstrap theme to BS 5.x.
Much changed since 3.x. and it'll take some time.

I still can benefit from suggestions and reviews at this time.
It also depends on a lot of old stuff like jQuery 1.x. I'll also try to get rid of all of those.

### CODE REVIEW

**Comment by quicklyweb** [comment]
I am also working on the same thing. So you can have a look at the progress live on http://www.quicklyweb.com

**Comment by andpavlenko** [comment]
@evrifaessa, @quicklyweb
How is work progress on migration Bootstrap 3 to 5? I would like to continue (after merge my first PR #1237).
Development was carried out in the branch `bootstrap-5`?

**Comment by evrifaessa** [comment]
> @evrifaessa, @quicklyweb
> How is work progress on migration Bootstrap 3 to 5? I would like to continue (after merge my first PR #1237).
> Development was carried out in the branch `bootstrap-5`?

Sure, you can work on it. And yes, I've pushed everything to that branch.

**Comment by evrifaessa** [comment]
Going with #1275 instead.

**Pull request closed without merging**
