### PR TITLE
HestiaCP support

### PR DESCRIPTION
**Pull request by jaapmarcus**
See https://github.com/jaapmarcus/boxbilling-hestia

If wanted I can also include "Vesta" module with some minor security improvements instead of the https://github.com/boxbilling/boxbilling/pull/1189

### CODE REVIEW

**Comment by BenNottelling** [comment]
I assume this is the one from
https://github.com/jaapmarcus/boxbilling-hestia

If so, I can't merge this, primarily because the github repo says it's a [GPL-2.0 License](https://github.com/jaapmarcus/boxbilling-hestia/blob/main/LICENSE), but the file itself says [Apache-2.0 ](https://github.com/jaapmarcus/boxbilling-hestia/blob/main/bb-libary/Server/Manager/Hestia.php#L6)

**Comment by jaapmarcus** [comment]
Removed the license from the repo. Probably accidentally added it when creating the repo...

**Comment by BenNottelling** [comment]
Alright well I spun up a new VPS, installed HestiaCP, and tried the server manager
And it works. And also HestiaCP gets a good first impression, so good job

**Review by andpavlenko — COMMENTED** [review]
Code styling is bad. PSR12 please.

**Comment by jaapmarcus** [comment]
> Code styling is bad. PSR12 please.
> Hestia is best for me now. Happy with this plugin.

Ran PHP CS fixer over the code for the Hestia plugin see:
https://github.com/boxbilling/boxbilling/pull/1256

**Pull request merged**
