### PR TITLE
Initial support for MyOwnFreeHost

### PR DESCRIPTION
**Pull request by evrifaessa**
So here it is, I've been working on this for some time, and I guess it's ready to become available to the public, even though there still are some missing things.

I used @HansAdema's [InfinityFreeHosting/mofh-client](https://github.com/InfinityFreeHosting/mofh-client). Additional details and Hans' own words on the integration can be found in #766.

First, let's start with some information. MyOwnFreeHost has it's own (and weird) system of storing user identifiers.
- When making API calls, you *must* use the 8-digit username that you've generated and submitted to MOFH while creating the account (a1b2c3d4)
- Then, it generates *another* username, which is basically like "<3 lettered reseller identifier>_<another, and different 8 char integer>" (abc_12345678)
- This makes everything weird, the user logs into the control panel with the abc_12345678 username, but we still need to store the other one somewhere
- While making API calls, the username you submit is not the one which user uses during their sign-in process, it's the one *you* generated in the beginning.
- Hence, you need to store it or hash the domain as I did.
- I used the "domainToID()" function to generate a unique hash for every domain, and we can be sure that it won't change unless the domain was changed
- Changing the domain is not supported by MyOwnFreeHost's API, so the domain probably won't be changed afterwards.

Let's see how we generate the hash, and get an 8-charactered string out of it:
We first generate an SHA-256 hash with the domain. And then, strip out the first 8 characters to generate a unique ID.
Let's understand it better with an example.
- So, here's the SHA-256 hash of 'boxbilling.com':
    - 0d3019bc07e517c2158a2c7eaccdf286fdececa78de7f736f2d1d602522e80c7
- We get the first 8 characters out of that, and it produces:
    - 0d3019bc
- Since it's a hash, it doesn't matter whether portions are discarded, but rather that the same input will produce the same hash.
- And the nice part, we don't need to store this in a database. As long as it's the same domain, it will always generate the same hash.

In this part, it leaves us with 3 different usernames:
- 1. The username we generate at the beginning, in `servicehosting->_generateUsername($domain_name)`. It generates a username by getting the first 7 letters of the domain and adding a random 0-9 number at the end (like 'boxbill1' from 'boxbilling.com')
- 2. The 8 charactered API username we generated from the domain hash. We'll use this for **all** of the API calls, this is very annoying. MOFH chose not to use the panel username (the 3rd one in this list) but chose to use this for all of the API calls instead. And this is not visible in the admin panel of MOFH or in anywhere else, you just need to store this, and you'll never have a chance to reset it once you've lost it.
- 3. The one MyOwnFreeHost sends to us, after activating the account. This is in an 'abc_12345678' format, the users will need to know this to log into their customer panel, and we need to store this as the 'username', and not the others instead.

The only bad thing here is, as MyOwnFreeHost sends us another username (in the 'abc_12345678' format, the third one in the list), we need to update our local dummy username (the first), with the one MOFH sent us, because users will have to use that username when they attempt to log into MOFH's panel.

But here's the problem, we can't update it. In the "`synchronizeAccount()`" function, and "`createAccount()`" function, I call the `$a->setUsername()` function to get BoxBilling to update that specific order's "username", it doesn't. So for now, the user signs up, gets an e-mail from MOFH, but the username in the e-mail and the one we store in BoxBilling is completely different, and we can't update it with the new one.

IMO, we can still merge it, it's still usable as the user gets an e-mail with the actual credentials, but we'll need to fix this in the future. As from what I can see, the `setUsername` function's not updating the username problem is not related with the module I wrote, but it's directly related with BB's `servicehosting` module itself.

### CODE REVIEW

**Review by timothygwebb — APPROVED** [review]
I have reviewed your changes.

**Comment by onyxcode** [comment]
I am very sorry to say that iFastNet/MOFH will not support BoxBilling.

image

**Comment by Wallvon** [comment]
> I am very sorry to say that iFastNet/MOFH will not support BoxBilling.
> 
> image

That does not say that they are not allowed to use the MOFH API in boxbilling, it just says that iFastNet will not provide any support for it.

**Comment by onyxcode** [comment]
> > I am very sorry to say that iFastNet/MOFH will not support BoxBilling.
> > image
> 
> That does not say that they are not allowed to use the MOFH API in boxbilling, it just says that iFastNet will not provide any support for it.

Hello, this was before you helped me lol
I apologize for any misunderstandings.

**Comment by ucanthvit** [comment]
Hello, I am needing some assistance with the MOFH integration.  I have the API set up correctly per the tests, but I keep getting "Failed Setup" orders with messages of "Order could not be activated after checkout due to error: Something went wrong getting the plan for the client, please ensure that the plan has been created in the reseller panel."

Here are the things I've tried to counter the "Failed Setup":

- Set up the plans in the reseller panel (with the same name) before I set them up in the boxbilling software
- Set up the plans in the reseller panel (with the same name) after I set them up in the boxbilling software
- Set up the hosting plans with 0 for email accounts
- Set up the hosting plans with (blank/null) for email accounts

I still can not get it integrated.  I also have multiple domains set up on MOFH and have used the correct/different API's for the different domains and none of them have worked.  Any help would be greatly appreciated.  I can provide any necessary screenshots, etc.

**Comment by ucanthvitgh** [comment]
Again, all of your help is greatly appreciated and thank you so much for everything you've done already!

I was digging through the code and believe I found the issue.  The plan name is hard-coded to "BoxBilling".  Once I created 1 plan named this, I am not getting a more expected error: "Order could not be activated after checkout due to error: The name servers for 12345whatever.com are not set to valid name servers."

- How would I go about getting this to pull/verify the plan name that I created in BoxBilling to lookup/match the plan name on the MOFH account?
- Also, how can I modify the request (signup form) to not require a FQD?  For example, above:  
> When making API calls, you must use the 8-digit username that you've generated and submitted to MOFH while creating the account (a1b2c3d4)

The "8-digit username" that you've generated is actually being set up as a subdomain on the MOFH account system (that is all this "username" is used for).  Later you get an actual login username (as you mentioned above) that is generated like: abc_12345678

With that in mind; I can let the client set up their own domain at a later time if they already have it, but would want to get their hosting account created ASAP.  That's why I was wondering how to modify the signup form accordingly.

**Pull request merged**
